### ISSUE TITLE
ACTIVIDAD 2

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-2-infografia-SandyMarissaGs#1]
[INFOGRAFIA DEL PROCESO DEL CONOCIMIENTO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-SandyMarissaGs/files/9466206/INFOGRAFIA.DEL.PROCESO.DEL.CONOCIMIENTO.pdf)

SANDY MARISSA GARCIA SANTIAGO.
GRUPO 1BS

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 2 INFOGRAFIA
DE 20% DE LA ACTIVIDAD OBTUVISTE 17.4 % DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
